MODULE DimensionTax;

REQUIRE Dimension, Tax;

EXTEND CLASS Range : Dimension;
EXTEND CLASS DimensionType {
     range 'Scale'
}
name (Range dimension) + = ISTRING [255] (staticCaption (tax (dimension)) + ', scale #' + number (dimension) + ', current rate (' + valueCurrentRate (dimension) + ')');
dimensionType (Range dimension) + = WHEN dimension IS Range THEN DimensionType.range;

id (Range dimension) + = ISTRING [20] (number (dimension));
